name: Test hello_world.nvt

on: push

jobs:
  test_hello:
    name: Test Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: pip install scons
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run test
        run: python3 ./Tests/hello_world.py
