name: Test hello_world.nvt

on: push

jobs:
  test_hello:
    name: Test Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: pip install scons
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        run: cmake . -B build -Dbuildtype=fast; cmake --build build;
      - name: Unit Tests
        run: ctest --test-dir build/test
      - name: End-to-End
        run: python3 ./test/Regressions.py
